version: '3.3'

services:
    mongo:
        image: mongo:4.4.1-bionic
        networks:
            - vividarmybot
        restart: always
        volumes:
            - ./mongo-data/:/data/db/:rw
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=R1PDlGcd2xiDvCHD5fZEMX7gBj82BCls
        ports:
            - 127.0.0.1:54017:27017
        command: --quiet

    discord:
        build: ./code
        networks:
            - vividarmybot
        volumes:
            - ./code/src/:/vividarmy/bot/src/:ro
        restart: always
        command: npm run discord-prod

    discord578:
        build: ./code
        networks:
            - vividarmybot
        volumes:
            - ./code/src/:/vividarmy/bot/src/:ro
        restart: always
        command: npm run discord-prod-578

    farm:
        build: ./code
        networks:
            - vividarmybot
        volumes:
            - ./code/src/:/vividarmy/bot/src/:ro
        restart: always
        command: npm run farm-prod

networks:
    vividarmybot:
        external:
            name: vividarmybot
