version: '3.3'

services:
    mongo:
        image: mongo:4.4.1-bionic
        networks:
            - vividarmybot
        restart: "no"
        volumes:
            - ./mongo-data/:/data/db/:rw
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=R1PDlGcd2xiDvCHD5fZEMX7gBj82BCls
        ports:
            - 127.0.0.1:54017:27017
        command: --quiet

networks:
    vividarmybot:
        external:
            name: vividarmybot
